language: node_js
node_js:
  - stable

cache:
  directories:
    - "node_modules"

branches:
  only:
    - main

before_install:
  - export TZ=Asia/Seoul
  - date
install:
  - npm install
  - npm run generate

script:
  - echo "Skipping tests"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN # Set in travis-ci.org dashboard, marked secure https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  target_branch: gh-pages
  local_dir: dist
  keep_history: true
  on:
    branch: main
